meta:
  version: '1.3'
  updatedAt: '2025-12-19T12:28:53.158Z'
preferences:
  general:
    language: zh
  appearance:
    wallpaper: https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop
  layout:
    showDock: true
    showDockEdit: false
    showSearchBar: true
    showPagination: true
integrations:
  ai:
    enabled: true
    providers:
      - id: '1766048302599'
        name: 小米
        apiUrl: https://api.xiaomimimo.com/v1/chat/completions
        apiKey: sk-s7pyjo6nw8gd5oi8a7z1ryc97cf66ouutonpps2ajv7059ym
        models: []
        customModels:
          - mimo-v2-flash
        temperature: 0.7
        maxTokens: 2000
    activeProviderId: '1766048302599'
    activeModel: mimo-v2-flash
searchEngines:
  - id: default
    name: Default
    searchUrl: ''
    icon: default
  - id: google
    name: Google
    searchUrl: https://www.google.com/search?q=%s
    suggestionUrl: https://suggestqueries.google.com/complete/search?client=firefox&q=%s
    icon: google
  - id: bing
    name: Bing
    searchUrl: https://www.bing.com/search?q=%s
    suggestionUrl: https://api.bing.com/qsonhs.aspx?q=%s
    icon: bing
  - id: baidu
    name: 百度
    searchUrl: https://www.baidu.com/s?wd=%s
    icon: baidu
  - id: duckduckgo
    name: DuckDuckGo
    searchUrl: https://duckduckgo.com/?q=%s
    suggestionUrl: https://duckduckgo.com/ac/?q=%s&type=list
    icon: duckduckgo
content:
  dock:
    - id: ai
      title: AI助手
      url: ''
      type: sys
      iconType: message-circle
      isApp: true
      color: ''
    - id: notes
      title: 便笺
      url: ''
      type: sys
      iconType: sticky-note
      isApp: true
      color: ''
    - id: store
      iconType: shopping-bag
      title: 应用商店
      isApp: true
      type: sys
      color: ''
      iconColor: '#EC4899'
      size:
        w: 1
        h: 1
    - id: calc
      title: 计算器
      url: ''
      type: sys
      iconType: calculator
      isApp: true
      color: ''
    - id: settings
      title: 设置
      url: ''
      type: sys
      iconType: settings
      isApp: true
      color: ''
  desktop:
    - id: 1765193991934
      title: 抖音
      url: https://www.douyin.com/
      type: auto
      customIcon: https://img.logo.dev/www.douyin.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765194042238
      title: bilibili
      url: https://www.bilibili.com/
      type: auto
      customIcon: https://img.logo.dev/www.bilibili.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765196356678
      title: 爱奇艺
      url: https://www.iqiyi.com/
      type: auto
      customIcon: https://unavatar.io/www.iqiyi.com?fallback=false
      color: ''
    - id: 1765196407071
      title: 腾讯视频
      url: https://v.qq.com/
      type: auto
      iconType: iconhorse
      customIcon: https://unavatar.io/v.qq.com?fallback=false
      color: ''
    - id: 1765196439382
      title: 芒果TV
      url: https://www.mgtv.com/
      type: auto
      iconType: unavatar
      customIcon: https://www.google.com/s2/favicons?domain=www.mgtv.com&sz=128
      color: ''
    - id: 1765196473480
      title: 优酷
      url: https://www.youku.com/
      type: auto
      customIcon: https://pp.myapp.com/ma_icon/0/icon_10197_1764143650/256
      color: ''
    - id: 1765195218788
      title: YouTube
      url: https://youtube.com
      type: auto
      customIcon: https://img.logo.dev/youtube.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765196938765
      title: GitHub
      url: https://github.com/
      type: auto
      iconType: logodev
      customIcon: https://img.logo.dev/github.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765196627763
      title: 猫眼
      url: https://www.maoyan.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_46766_1762161597/256
      color: ''
    - id: 1765196675813
      title: 猫眼专业版
      url: https://piaofang.maoyan.com/dashboard
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_12124845_1763969293/256
      color: ''
    - id: 1765198295426
      title: QQ音乐
      url: https://y.qq.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_6259_1765190757/256
      color: ''
    - id: 1765198343668
      title: 网易云音乐
      url: https://music.163.com/
      type: auto
      iconType: clearbit
      customIcon: https://img.logo.dev/music.163.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
      x: 3
      'y': 1
      page: 0
      size:
        w: 1
        h: 1
      isApp: false
    - id: 1765198362240
      title: 喜马拉雅
      url: https://www.ximalaya.com/
      type: auto
      iconType: unavatar
      color: from-orange-500 to-orange-700
    - title: Calendar
      type: widget
      widgetType: iframe
      widgetContent: https://moduqishi.github.io/GrassTab-Store/widgets/calendar.html
      size:
        w: 2
        h: 2
      color: from-white to-gray-100
      isApp: false
      id: 1766147162859
    - id: 1765194325676
      title: Hugging Face
      url: https://huggingface.co/
      type: auto
      customIcon: https://img.logo.dev/huggingface.co?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765197985565
      title: 腾讯文档
      url: https://docs.qq.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_52666442_1764918437/256
      color: ''
    - id: 1765195013236
      title: 菜鸟教程
      url: https://runoob.com
      type: auto
      customIcon: https://icon.horse/icon/runoob.com
      color: ''
    - id: 1765195159657
      title: 学习通
      url: https://i.chaoxing.com/base
      type: auto
      customIcon: https://pp.myapp.com/ma_icon/0/icon_12269313_1763524961/256
      color: ''
    - id: 1765196315850
      title: PTA
      url: https://pintia.cn/
      type: auto
      iconType: unavatar
      color: from-purple-500 to-purple-700
    - id: 1765195317537
      title: Gemini
      url: https://gemini.google.com
      type: auto
      customIcon: https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128
      color: ''
    - id: 1765195544793
      title: ChatGPT
      url: https://chatgpt.com/
      type: auto
      iconType: unavatar
      color: from-green-500 to-teal-600
    - id: 1765195568334
      title: Claude
      url: https://claude.ai/
      type: auto
      iconType: unavatar
      customIcon: https://www.google.com/s2/favicons?domain=claude.ai&sz=128
      color: ''
    - id: 1765195610054
      title: Meta AI
      url: https://meta.ai
      type: auto
      customIcon: https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/59/06/f3/5906f39d-ff2a-41ef-873f-57d2aa989aa6/Placeholder.mill/200x200bb-75.webp
      color: ''
    - id: 1765195462659
      title: Doubao
      url: https://www.doubao.com
      type: auto
      customIcon: https://pp.myapp.com/ma_icon/0/icon_54330344_1764673656/256
      color: ''
    - id: 1765195675002
      title: DeepSeek
      url: https://chat.deepseek.com/
      type: auto
      iconType: unavatar
      color: from-blue-600 to-indigo-700
    - id: 1765195700715
      title: Kimi
      url: https://www.kimi.com/
      type: auto
      iconType: unavatar
      color: from-cyan-500 to-blue-600
    - id: 1765195771345
      title: 智谱清言
      url: https://chatglm.cn/
      type: auto
      iconType: unavatar
      color: from-blue-500 to-blue-700
    - id: 1765195807855
      title: Qwen Chat
      url: https://chat.qwen.ai/
      type: auto
      customIcon: https://unavatar.io/chat.qwen.ai?fallback=false
      color: ''
    - id: 1765195880965
      title: 知乎
      url: https://www.zhihu.com/
      type: auto
      iconType: logodev
      color: from-blue-600 to-blue-800
    - id: 1765195895356
      title: 小红书
      url: https://www.xiaohongshu.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_10868231_1764898028/256
      color: ''
    - id: 1765196198468
      title: 斗鱼
      url: https://www.douyu.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_10921913_1764658904/256
      color: ''
    - id: 1765198245086
      title: 彩云天气
      url: https://caiyunapp.com/map/
      type: auto
      iconType: unavatar
      color: from-blue-400 to-blue-600
    - id: 1765196606382
      title: Douban
      url: https://movie.douban.com/
      type: auto
      customIcon: https://unavatar.io/movie.douban.com?fallback=false
      color: ''
    - id: 1765196781842
      title: 飞书
      url: https://www.feishu.cn/
      type: auto
      iconType: unavatar
      color: from-blue-500 to-blue-700
    - id: 1765196823194
      title: 企业微信
      url: https://work.weixin.qq.com/
      type: auto
      customIcon: https://pp.myapp.com/ma_icon/0/icon_42270467_1763431984/256
      color: ''
    - id: 1765196874884
      title: 腾讯会议
      url: https://meeting.tencent.com/
      type: auto
      iconType: unavatar
      customIcon: https://icons.duckduckgo.com/ip3/meeting.tencent.com.ico
      color: ''
    - id: 1765197323190
      title: 微博热搜
      url: https://weibo.com/newlogin?tabtype=search&gid=&openLoginLayer=0&url=
      type: auto
      customIcon: https://img.logo.dev/weibo.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765197603278
      title: 少数派
      url: https://sspai.com/
      type: auto
      iconType: unavatar
      color: from-red-500 to-red-700
    - id: 1765197660862
      title: 百度
      url: https://www.baidu.com/
      type: auto
      iconType: clearbit
      customIcon: https://unavatar.io/www.baidu.com?fallback=false
      color: ''
    - id: 1765197680292
      title: Google
      url: https://google.com
      type: auto
      customIcon: https://unavatar.io/google.com?fallback=false
      color: ''
    - id: 1765195392428
      title: Unsplash
      url: https://unsplash.com/
      type: auto
      iconType: unavatar
      color: from-gray-700 to-gray-900
      x: 7
      'y': 4
      page: 0
      size:
        w: 1
        h: 1
      customIcon: https://img.logo.dev/unsplash.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      isApp: false
    - id: 1765197786241
      title: 123云盘
      url: https://www.123pan.com/
      type: auto
      iconType: unavatar
      color: from-blue-500 to-blue-700
    - id: 1765197807912
      title: 百度网盘
      url: https://pan.baidu.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_116071_1764839081/256
      color: ''
    - id: 1765197868543
      title: 淘宝
      url: https://www.taobao.com/
      type: auto
      iconType: clearbit
      customIcon: https://icon.horse/icon/www.taobao.com
      color: ''
    - id: 1765197908143
      title: 什么值得买
      url: https://www.smzdm.com/
      type: auto
      customIcon: https://unavatar.io/www.smzdm.com?fallback=false
      color: ''
    - id: 1765197935324
      title: 今日头条
      url: https://www.toutiao.com/
      type: auto
      iconType: logodev
      customIcon: https://img.logo.dev/www.toutiao.com?token=pk_dwKHjzWUSauY_R0n8QQmKQ
      color: ''
    - id: 1765198092873
      title: 携程
      url: https://www.ctrip.com/
      type: auto
      iconType: unavatar
      color: from-blue-500 to-blue-700
    - id: 1765198181335
      title: 高德地图
      url: https://www.amap.com/
      type: auto
      iconType: unavatar
      customIcon: https://pp.myapp.com/ma_icon/0/icon_7678_1765185623/256
      color: ''
    - id: 1765198269787
      title: 和风天气
      url: https://www.qweather.com/
      type: auto
      iconType: unavatar
      color: from-blue-400 to-cyan-600
    - id: 1765197356299
      title: Figma
      url: https://www.figma.com/
      type: auto
      iconType: unavatar
      color: from-purple-500 to-pink-600
    - title: VS Code
      url: https://vscode.dev
      type: custom
      isApp: true
      color: from-blue-500 to-blue-600
      iconType: unavatar
      customIcon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png
      id: 1766147106940
data:
  notes: ''
